#!/bin/sh
./toc.py index.md install.md usage.md key_assign.md settings.md layouts.md roomazi.md altgr.md > toc.txt
./md2html.py index.md altgr.md install.md
./md2html.py install.md index.md usage.md
./md2html.py usage.md install.md key_assign.md
./md2html.py key_assign.md usage.md settings.md
./md2html.py settings.md key_assign.md layouts.md
./md2html.py layouts.md settings.md roomazi.md
./md2html.py roomazi.md layouts.md altgr.md
./md2html.py altgr.md roomazi.md index.md
